import { Form, router } from '@inertiajs/react';
import { FormEvent, useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { formatCurrency, formatDateTime } from '@/lib/money';

type Transfer = { id: number; type: string; status: string; amount: string; fee: string; currency: string; customer: string; source_account: string; recipient: string | null; bank_name: string | null; description: string | null; created_at: string | null };
type Props = { transfers: { data: Transfer[]; links: Array<{ url: string | null; label: string; active: boolean }>; total: number }; filters: { status: string; type: string } };

export default function TransferLedgerEditor({ transfers, filters }: Props) {
    const [status, setStatus] = useState(filters.status); const [type, setType] = useState(filters.type);
    function filter(event: FormEvent) { event.preventDefault(); router.get('/admin/transfers', { status: status || undefined, type: type || undefined }, { preserveState: true, replace: true }); }
    return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Transfer ledger</h1><p className="mt-1 text-sm text-muted-foreground">Review and safely correct transfer amounts, descriptions, settlement statuses, and timestamps.</p></div><form onSubmit={filter} className="flex flex-wrap gap-2"><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option value="">All statuses</option><option value="completed">Completed</option><option value="pending">Pending</option><option value="failed">Failed</option></select><select value={type} onChange={(event) => setType(event.target.value)} className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option value="">All types</option><option value="internal">Internal</option><option value="domestic">Domestic</option><option value="wire">Wire</option></select><Button type="submit">Filter</Button></form><Card><CardHeader><CardTitle>Transfers</CardTitle><CardDescription>{transfers.total} records</CardDescription></CardHeader><CardContent className="grid gap-4">{transfers.data.map((transfer) => <TransferEditor key={transfer.id} transfer={transfer} />)}{transfers.data.length === 0 && <p className="py-10 text-center text-sm text-muted-foreground">No transfers match these filters.</p>}<div className="flex flex-wrap gap-2">{transfers.links.map((link, index) => <Button key={index} size="sm" variant={link.active ? 'default' : 'outline'} disabled={!link.url} onClick={() => link.url && router.get(link.url)} dangerouslySetInnerHTML={{ __html: link.label }} />)}</div></CardContent></Card></div>;
}

function TransferEditor({ transfer }: { transfer: Transfer }) {
    const timestamp = transfer.created_at ? new Date(transfer.created_at) : new Date();
    const date = timestamp.toISOString().slice(0, 10); const time = timestamp.toTimeString().slice(0, 5);
    return <div className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold capitalize">{transfer.type} transfer</p><Badge variant={transfer.status === 'failed' ? 'destructive' : transfer.status === 'completed' ? 'default' : 'secondary'} className="capitalize">{transfer.status}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{transfer.customer} · {transfer.source_account} → {transfer.recipient ?? 'Recipient'}</p><p className="text-xs text-muted-foreground">{formatDateTime(transfer.created_at)}{transfer.bank_name ? ` · ${transfer.bank_name}` : ''}</p></div><div className="text-right"><p className="font-semibold">{formatCurrency(transfer.amount, transfer.currency)}</p><p className="text-xs text-muted-foreground">Fee {formatCurrency(transfer.fee, transfer.currency)}</p></div></div><Form action={`/admin/transfers/${transfer.id}`} method="patch" onSubmit={(event) => { if (!window.confirm('Save these transfer changes? Status changes reconcile linked balances and timestamp changes update linked history.')) event.preventDefault(); }} className="mt-4 grid gap-3 border-t pt-4 sm:grid-cols-3">{({ processing, errors }) => <><Field id={`description-${transfer.id}`} name="description" label="Transfer description" defaultValue={transfer.description ?? ''} error={errors.description} /><Field id={`amount-${transfer.id}`} name="amount" label={`Amount (${transfer.currency})`} type="number" defaultValue={transfer.amount.replace(/[$,]/g, '')} error={errors.amount} readOnly={transfer.status !== 'completed'} /><Field id={`status-${transfer.id}`} name="status" label="Transfer status" type="select" defaultValue={transfer.status === 'failed' ? 'failed' : 'completed'} error={errors.status} /><Field id={`date-${transfer.id}`} name="date" label="Transfer date" type="date" defaultValue={date} error={errors.date} /><Field id={`time-${transfer.id}`} name="time" label="Transfer time" type="time" defaultValue={time} error={errors.time} /><div className="flex items-end justify-end"><Button disabled={processing}>{processing ? 'Saving…' : 'Save transfer changes'}</Button></div><p className="text-xs text-muted-foreground sm:col-span-3">For safety, save an amount correction separately from changing the status.</p></>}</Form></div>;
}

function Field({ id, name, label, type = 'text', defaultValue, error, readOnly = false }: { id: string; name: string; label: string; type?: string; defaultValue: string; error?: string; readOnly?: boolean }) { return <div className="grid gap-2"><Label htmlFor={id}>{label}</Label>{type === 'select' ? <select id={id} name={name} defaultValue={defaultValue} className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option value="completed">Completed</option><option value="failed">Failed</option></select> : <Input id={id} name={name} type={type} min={type === 'number' ? '0.01' : undefined} step={type === 'number' ? '0.01' : undefined} defaultValue={defaultValue} readOnly={readOnly} required={name !== 'description'} />}<p className="text-xs text-destructive">{error}</p></div>; }
