import { Form, Head, Link } from '@inertiajs/react';
import { ArrowLeft, Clock3, FilePenLine, History, ShieldCheck } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { formatCurrency, formatDateTime } from '@/lib/money';

type Audit = { id: number; admin_name: string; previous_values: { date_time?: string; amount?: string; status?: string }; new_values: { date_time?: string; amount?: string; status?: string }; reason: string; created_at: string | null };
type Props = { transaction: { id: number; customer_name: string; account_name: string; currency: string; type: string; description: string | null; amount: string; status: string; created_at: string | null; is_transfer_linked: boolean }; statuses: string[]; audits: Audit[] };

export default function AdminTransactionShow({ transaction, statuses, audits }: Props) {
    const timestamp = transaction.created_at ? new Date(transaction.created_at) : new Date();
    const dateValue = timestamp.toISOString().slice(0, 10);
    const timeValue = timestamp.toTimeString().slice(0, 5);

    return <><Head title={`Admin · Transaction #${transaction.id}`} /><div className="mx-auto max-w-5xl space-y-6">
        <div><Button variant="ghost" size="sm" className="-ml-2 mb-2" asChild><Link href="/admin/transactions"><ArrowLeft className="size-4" />Back to transactions</Link></Button><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">Edit transaction</h1><p className="mt-1 text-sm text-muted-foreground">Transaction #{transaction.id} · {transaction.customer_name}</p></div><Badge variant="secondary" className="capitalize">{transaction.status}</Badge></div></div>
        <Card className="border shadow-sm"><CardHeader><CardTitle>Transaction context</CardTitle><CardDescription>These details are read-only and identify the original ledger record.</CardDescription></CardHeader><CardContent className="grid gap-4 text-sm sm:grid-cols-3"><Detail label="Customer" value={transaction.customer_name} /><Detail label="Account" value={transaction.account_name} /><Detail label="Type" value={transaction.type} /><Detail label="Description" value={transaction.description ?? '—'} /><Detail label="Current amount" value={formatCurrency(transaction.amount, transaction.currency)} /><Detail label="Current date/time" value={formatDateTime(transaction.created_at)} /></CardContent></Card>
        <Card className="border shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><FilePenLine className="size-5 text-brand" />Edit details</CardTitle><CardDescription>{transaction.is_transfer_linked ? 'This transaction belongs to a transfer. Its amount and status are locked to protect the linked transfer ledger; you may correct its timestamp.' : 'Changes to amount or status are reconciled against the stored account balance and recorded in audit history.'}</CardDescription></CardHeader><CardContent><Form action={`/admin/transactions/${transaction.id}/financial`} method="patch" onSubmit={(event) => { if (!window.confirm('Save these transaction changes? This will create a permanent audit record.')) event.preventDefault(); }} className="grid gap-5 sm:grid-cols-2">{({ processing, errors }) => <>
            <Field name="date" label="Transaction date" type="date" defaultValue={dateValue} error={errors.date} /><Field name="time" label="Transaction time" type="time" defaultValue={timeValue} error={errors.time} />
            <div className="grid gap-2"><Label htmlFor="amount">Amount ({transaction.currency})</Label><Input id="amount" name="amount" type="number" min="0.01" step="0.01" defaultValue={transaction.amount} readOnly={transaction.is_transfer_linked} required /><p className="text-xs text-destructive">{errors.amount}</p></div>
            <div className="grid gap-2"><Label htmlFor="status">Transaction status</Label>{transaction.is_transfer_linked ? <Input id="status" name="status" defaultValue={transaction.status} readOnly /> : <select id="status" name="status" defaultValue={transaction.status} className="h-9 rounded-md border border-input bg-background px-3 text-sm">{statuses.map((status) => <option key={status} value={status}>{status.charAt(0).toUpperCase() + status.slice(1)}</option>)}</select>}<p className="text-xs text-destructive">{errors.status}</p></div>
            <div className="grid gap-2 sm:col-span-2"><Label htmlFor="reason">Reason for change</Label><textarea id="reason" name="reason" required minLength={5} maxLength={500} className="min-h-24 rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="Explain why this correction is required." /><p className="text-xs text-destructive">{errors.reason}</p></div>
            <div className="flex flex-wrap justify-end gap-2 sm:col-span-2"><Button type="button" variant="outline" asChild><Link href="/admin/transactions">Cancel</Link></Button><Button disabled={processing}>{processing ? 'Saving changes…' : 'Save changes'}</Button></div>
        </>}</Form></CardContent></Card>
        <Card className="border shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><History className="size-5 text-brand" />Edit history</CardTitle><CardDescription>Internal audit records are visible only to administrators.</CardDescription></CardHeader><CardContent>{audits.length === 0 ? <p className="py-6 text-center text-sm text-muted-foreground">No edits have been recorded.</p> : <div className="divide-y">{audits.map((audit) => <div key={audit.id} className="py-4 first:pt-0 last:pb-0"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-medium">{audit.admin_name}</p><p className="text-sm text-muted-foreground">{audit.reason}</p></div><p className="text-xs text-muted-foreground"><Clock3 className="mr-1 inline size-3" />{formatDateTime(audit.created_at)}</p></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><Change label="Date/time" oldValue={audit.previous_values.date_time ? formatDateTime(audit.previous_values.date_time) : '—'} newValue={audit.new_values.date_time ? formatDateTime(audit.new_values.date_time) : '—'} /><Change label="Amount" oldValue={audit.previous_values.amount ? formatCurrency(audit.previous_values.amount, transaction.currency) : '—'} newValue={audit.new_values.amount ? formatCurrency(audit.new_values.amount, transaction.currency) : '—'} /><Change label="Status" oldValue={audit.previous_values.status ?? '—'} newValue={audit.new_values.status ?? '—'} /></div></div>)}</div>}</CardContent></Card>
        <div className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-4 text-brand" />Every successful update records the prior values, new values, reason, and administrator.</div>
    </div></>;
}

function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
function Change({ label, oldValue, newValue }: { label: string; oldValue: string; newValue: string }) { return <div className="rounded-lg bg-muted/50 p-2"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xs line-through text-muted-foreground">{oldValue}</p><p className="font-medium">{newValue}</p></div>; }
function Field({ name, label, type, defaultValue, error }: { name: string; label: string; type: string; defaultValue: string; error?: string }) { return <div className="grid gap-2"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} defaultValue={defaultValue} required /><p className="text-xs text-destructive">{error}</p></div>; }

AdminTransactionShow.layout = { breadcrumbs: [{ title: 'Admin', href: '/admin' }, { title: 'Transactions', href: '/admin/transactions' }, { title: 'Edit transaction', href: '#' }] };
