import { Form, Head, Link } from '@inertiajs/react';
import { ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

type Row = { id: number; customer: string; customer_id: number; email: string; purpose: string; status: string; requested_at: string; expires_at: string; attempt_count: number; maximum_attempts: number; transfer_id?: number; development_code?: string | null };

export default function OtpVerificationIndex({ records, showDevelopmentOtp }: { records: { data: Row[] }; showDevelopmentOtp: boolean }) {
    return <><Head title="Admin · Security verification" /><div className="space-y-6"><div><div className="flex items-center gap-2"><ShieldCheck className="size-6 text-primary" /><h1 className="text-2xl font-semibold">OTP / Security Verification</h1></div><p className="mt-1 text-sm text-muted-foreground">Monitor verification lifecycle events. {showDevelopmentOtp ? 'Development codes are visible only in local mode.' : 'Codes are never displayed.'}</p></div><Card><CardHeader><CardTitle>Verification events</CardTitle><CardDescription>Customer login and transfer authorizations, including status and attempts.</CardDescription></CardHeader><CardContent className="space-y-3">{records.data.map((row) => <div className="rounded-xl border p-4" key={row.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{row.customer} <span className="text-muted-foreground">#{row.customer_id}</span></p><p className="text-sm text-muted-foreground">{row.email} · {row.purpose === 'transfer' ? 'Transfer authorization' : 'Login'}</p><p className="mt-1 text-xs text-muted-foreground">Requested {new Date(row.requested_at).toLocaleString()} · Expires {new Date(row.expires_at).toLocaleString()} · {row.attempt_count}/{row.maximum_attempts} attempts</p>{showDevelopmentOtp && row.development_code && <p className="mt-2 font-mono text-sm font-semibold text-primary">Development OTP: {row.development_code}</p>}</div><div className="flex items-center gap-2"><span className="rounded-full bg-muted px-3 py-1 text-xs font-medium capitalize">{row.status}</span>{row.status === 'pending' && <Form action={`/admin/otp-verifications/${row.id}/invalidate`} method="post">{({ processing }) => <Button size="sm" variant="outline" disabled={processing}>Invalidate</Button>}</Form>}{row.transfer_id && <Link className="text-sm text-primary underline" href="/admin/transfers">Related transfer</Link>}</div></div></div>)}{records.data.length === 0 && <p className="py-8 text-center text-sm text-muted-foreground">No OTP verification events yet.</p>}</CardContent></Card></div></>;
}

OtpVerificationIndex.layout = { breadcrumbs: [{ title: 'Admin', href: '/admin' }, { title: 'Security verification', href: '/admin/otp-verifications' }] };
