import { Form, Head } from '@inertiajs/react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { formatCurrency, formatDateTime } from '@/lib/money';

type Account = { id: number; name: string; balance: string; currency: string; user_name: string };
type Transaction = { id: number; type: string; amount: string; description: string | null; account_name: string; created_at: string | null };

export default function AdminTransactions({ accounts, transactions }: { accounts: Account[]; transactions: Transaction[] }) {
    return <><Head title="Admin · Transactions" /><div className="space-y-6"><div><h1 className="text-2xl font-semibold">Transaction manager</h1><p className="mt-1 text-sm text-muted-foreground">Generate dated ledger activity and edit transaction descriptions.</p></div><Card><CardHeader><CardTitle>Generate transactions</CardTitle><CardDescription>Create up to 100 credits or debits, distributed across a date range.</CardDescription></CardHeader><CardContent><Form action="/admin/transactions/generate" method="post" className="grid gap-4 sm:grid-cols-2">{({ processing, errors }) => <><div className="grid gap-2 sm:col-span-2"><Label>Account</Label><select name="account_id" className="h-9 rounded-md border border-input bg-background px-3 text-sm" required><option value="">Select account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.user_name} · {account.name} ({formatCurrency(account.balance, account.currency)})</option>)}</select><p className="text-xs text-destructive">{errors.account_id}</p></div><Field name="amount" label="Amount per transaction" type="number" /><div className="grid gap-2"><Label>Type</Label><select name="transaction_type" className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option value="Credit">Credit</option><option value="Debit">Debit</option></select></div><Field name="count" label="Count (1–100)" type="number" defaultValue="10" /><Field name="start_date" label="Start date" type="date" /><Field name="end_date" label="End date" type="date" /><Field name="description" label="Description" required={false} /><div className="flex items-end"><Button disabled={processing}>Generate transactions</Button></div></>}</Form></CardContent></Card><Card><CardHeader><CardTitle>Recent ledger activity</CardTitle></CardHeader><CardContent><div className="grid gap-3">{transactions.map((transaction) => <div key={transaction.id} className="rounded-xl border p-3"><div className="flex justify-between gap-4"><div><p className="font-medium">{transaction.description ?? 'Transaction'}</p><p className="text-sm text-muted-foreground">{transaction.type} · {transaction.account_name} · {formatDateTime(transaction.created_at)}</p></div><p className="font-semibold">{formatCurrency(transaction.amount)}</p></div><Form action={`/admin/transactions/${transaction.id}`} method="patch" className="mt-3 flex gap-2">{({ processing }) => <><Input name="description" defaultValue={transaction.description ?? ''} aria-label="Transaction description" /><Button size="sm" variant="outline" disabled={processing}>Save</Button></>}</Form></div>)}</div></CardContent></Card></div></>;
}

function Field({ name, label, type = 'text', defaultValue, required = true }: { name: string; label: string; type?: string; defaultValue?: string; required?: boolean }) { return <div className="grid gap-2"><Label>{label}</Label><Input name={name} type={type} step={type === 'number' ? '0.01' : undefined} min={type === 'number' ? '0' : undefined} defaultValue={defaultValue} required={required} /></div>; }

AdminTransactions.layout = { breadcrumbs: [{ title: 'Admin', href: '/admin' }, { title: 'Transactions', href: '/admin/transactions' }] };
